##FROM php:8.2-apache
##RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

FROM php:7.4-apache
FROM python:3

RUN docker-php-ext-install mysqli
RUN docker-php-ext-enable mysqli
RUN pip install --no-cache-dir -r requirements.txt
